services:
  haproxy:
    image: haproxy:2.8
    depends_on:
      certbot_self_signed:
        condition: service_completed_successfully
    healthcheck:
      test: |
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/80; echo -e "GET /health HTTP/1.1\nConnection: close\n" >&3; cat <&3 | grep -q "200 OK"'
      interval: 5s
    volumes:
      - ./conf-haproxy:/usr/local/etc/haproxy/
      - ./data-backend-certs/:/etc/ssl/backend-certs/
      - data-certificates:/etc/ssl/private/
    ports:
      - '80:80'
      - '443:443'

  certbot_self_signed:
    image: local/certbot_self_signed
    build:
      context: docker/certbot_self_signed
    volumes:
      - data-certificates:/etc/ssl/private/
    env_file:
      - certbot.env

  certbot_letsencrypt:
    image: local/certbot_letsencrypt
    build:
      context: docker/certbot_letsencrypt
    depends_on:
      haproxy:
        condition: service_healthy
    volumes:
      - data-letsencrypt:/etc/letsencrypt/
      - data-certificates:/etc/ssl/private/
    env_file:
      - certbot.env

volumes:
  data-letsencrypt:
  data-certificates:
